Calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("DurgaTemp_Calculator.urls")),
]

handler404 = 'DurgaTemp_Calculator.views.my_404_view'

DurgaTemp_Calculator/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import temperature_converter, convert_temperature, conversion_history, register, login_view, logout_view, delete, delete_all

app_name = "home"

urlpatterns = [
    path('', login_required(temperature_converter), name='temperature_converter'),
    path('convert_temperature/', convert_temperature, name='convert_temperature'),
    path('history/', conversion_history, name='history'),
    path('account/signup/', register, name='register'),
    path('account/login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/<int:id>/', delete, name='delete'),
    path('delete/', delete_all, name='delete_all')
]

DurgaTemp_Calculator/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class History(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    temperature = models.FloatField()
    from_unit = models.CharField(max_length=25)
    converted = models.FloatField()
    to_unit = models.CharField(max_length=25)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return f'Conversion from: {self.from_unit} to {self.to_unit} on {self.created_at}'

DurgaTemp_Calculator/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from DurgaTemp_Calculator.models import History


# Create your views here.

@login_required(login_url='account/login/')
def temperature_converter(request):
    return render(request, 'home/index.html')

def my_404_view(request, exception):
    return render(request, 'home/404.html')

@login_required(login_url='account/login/')
def convert_temperature(request):
    temperature = request.GET.get('temperature', '0')
    from_unit = request.GET.get('from_unit')
    to_unit = request.GET.get('to_unit')

    try:
        temperature = float(temperature)
    except ValueError:
        return JsonResponse({'error': 'Invalid temperature value'})

    if from_unit == 'celsius':
        if to_unit == 'fahrenheit':
            converted = (temperature * 9/5) + 32
        elif to_unit == 'kelvin':
            converted = temperature + 273.15
        else:
            converted = temperature
    elif from_unit == 'fahrenheit':
        if to_unit == 'celsius':
            converted = (temperature - 32) * 5/9
        elif to_unit == 'kelvin':
            converted = (temperature + 459.67) * 5 / 9
        else:
            converted = temperature
    elif from_unit == 'kelvin':
        if to_unit == 'celsius':
            converted = temperature - 273.15
        elif to_unit == 'fahrenheit':
            converted = (temperature * 1.8) - 459.67
        else:
           converted = temperature
    else:
        return JsonResponse({'error': 'Invalid source unit'})

    conversion_history_result = History(
        User = request.user,
        temperature = temperature,
        from_unit = from_unit,
        to_unit = to_unit,
        converted = converted
    )
    conversion_history_result.save()

    return JsonResponse({'converted': round(converted, 0)})

@login_required(login_url='account/login/')
def conversion_history(request):
    conversion_history_results = History.objects.all()

    conversion_history_results = History.objects.filter(
        User = request.user,
        temperature__isnull=False,
        from_unit__isnull=False,
        to_unit__isnull=False,
    )

    for conversion_history_result in conversion_history_results:
        existing_conversion_history_results = History.objects.filter(
            User=conversion_history_result.User,
            temperature=conversion_history_result.temperature,
            from_unit=conversion_history_result.from_unit,
            to_unit=conversion_history_result.to_unit
        )

        if len(existing_conversion_history_results) > 1:
            conversion_history_result.delete()
            return redirect('home:history')

    return render(request, 'home/history.html', {
        'conversion_history_results': conversion_history_results
    })

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('confirm_password')

        if password2 == password:
            new_user = User.objects.create_user(username=username, first_name=firstname, last_name=lastname, email=email, password=password)
            new_user.save()
            return redirect('home:login')

    if request.user.is_authenticated:
        return redirect('home:temperature_converter')    

    return render(request, 'account/register.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        User = authenticate(request, username=username, password=password)
        if User is not None:
            login(request, User)
            return redirect('home:temperature_converter')

    if request.user.is_authenticated:
        return redirect('home:temperature_converter')

    return render(request, 'account/login.html')

def logout_view(request):
    logout(request)
    return redirect('home:login')

@login_required(login_url='account/login/')
def delete(request, id):
    remove_item = History.objects.get(id=id, User=request.user)  
    if request.method == 'POST':
        remove_item.delete()
        return redirect('home:history')    
    else:
        return render(request, 'home/delete.html', {'remove_item': remove_item})

  

@login_required(login_url='account/login/')
def delete_all(request):
    if request.method == 'GET':  
        history = History.objects.all()
        conversion_history = history.filter(User=request.user)
        if conversion_history:
            conversion_history.delete()
            return redirect('home:history')    
        return render(request, 'home/delete_all.html', {'history':history, 'conversion_history':conversion_history})

DurgaTemp_Calculator/templates/home/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <title>Durga-Temp Calulator</title>
</head>
<body>
    <div class="delete">
        <header>
            <nav>
                <div class="name-greeting-holder">
                    <h2 class="logo">Durga</h2>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="inner-container">
                <h2>Hi {{request.user}}</h2>
                <h3>You are about to delete this conversion you did.</h3>
                <form method="post">
                    {% csrf_token %}
                    <p class="p">Are you sure you want to delete it?</p>
                    {% if remove_item %}
                    <span>Conversion <br> <p>{{remove_item.temperature}}<sup>&compfn;</sup> {{remove_item.from_unit}} equals to {{remove_item.converted}}<sup>&compfn;</sup> {{remove_item.to_unit}}</p></span>
                    {% endif %}
                    <div class="buttons">
                        <a href="{% url 'home:history' %}">No, back</a>
                        <button type="submit">Yes, sure</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="attribution-holder">
            <p class="attribution">&copy; copyright 2023 coded by <span>Boss(Aniebiet)</span></p>
        </div>
    </div>
</body>
</html>

DurgaTemp_Calculator/templates/home/delete_all.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <title>Durga-Temp Calulator</title>
</head>
<body>
    <div class="delete-all">
        <header>
            <nav>
                <div class="name-greeting-holder">
                    <h2 class="logo">Durga</h2>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="inner-container">
                <form method="post" action="{% url 'home:history' %}">
                    {% csrf_token %}
                    <div class="buttons">
                        <button type="submit">Yes, sure</button>
                        <a href="{% url 'home:history' %}">No, back</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="attribution-holder">
            <p class="attribution">&copy; copyright 2023 coded by <span>Boss(Aniebiet)</span></p>
        </div>
    </div>
</body>
</html>

DurgaTemp_Calculator/templates/home/history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/style.js' %}"></script>
    <title>Durga-Temp Calulator || My History</title>
</head>
<body>
    <div class="history-holder">
        <div class="container">
            <div class="history-title">
                <h1>Conversion History</h1>
            </div>
            <div class="history-conversion-holder">
                <div class="history">
                    <div class="delete-history">
                        <a href="{% url 'home:temperature_converter' %}">back</a>
                        {% if conversion_history_results %}
                            <a href="{% url 'home:delete_all' %}">delete all</a>
                        {% endif %}
                    </div>
                    <div class="history-flex" id="flex">
                        {% if conversion_history_results %}
                            <table class="first-table" id="table">
                                <thead>
                                    <tr>
                                        <th class="th-col">My conversions</th>
                                        <th class="th-col-2">Date and Time</th>
                                    </tr>
                                </thead>
                            </table>
                            {% for conversion_history_result in conversion_history_results %}
                                <table class="conversions">
                                    <tbody>
                                        <tr>
                                            <td class="td-row">{{conversion_history_result.temperature}}<sup>&compfn;</sup> {{conversion_history_result.from_unit}} equals to {{conversion_history_result.converted}}<sup>&compfn;</sup> {{conversion_history_result.to_unit}}</td>
                                            <td>{{conversion_history_result.created_at}}</td>
                                            <td class="del"><a href="{% url 'home:delete' conversion_history_result.id %}">&times;</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            {% endfor %}
                        {% else %}
                            <div>
                              <p>You have not done any conversions yet.</p>
                            </div>
                          {% endif %}
                    </div>
                </div>
                <footer class="attribution-holder">
                    <p class="attribution">&copy; copyright 2023 coded by <span>Boss(Aniebiet)</span></p>
                </footer>
           </div>
        </div>
    </div>
</body>
</html>

DurgaTemp_Calculator/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <title>Durga-Temp Calulator</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/style.js' %}"></script>
</head>
<body>
    <div class="temperature-calculator">
        <div class="container">
            {% if request.user.is_authenticated %}
                <header>
                    <nav>
                        <div class="name-greeting-holder">
                            <h2 class="logo">Durga</h2>
                            <ul>
                                <li><a href="{% url 'home:history' %}">history</a></li>
                                <li><a href="{% url 'home:logout' %}">logout</a></li>
                            </ul>
                        </div>
                    </nav>
                </header>
            {% endif %}
            <div class="greeting">
                <p>
                    <span id="greeting"></span><span class="user">{{request.user}}</span><span class="blink">|</span>
                </p>
            </div>
            <div class="temperature-calculator-holder">
                <div class="temperature-holder">
                    <div class="calculator-keys">
                        <div class="first-keys">
                            <button class="del-key">d</button>
                            <button class="del-all-key">del</button>
                            <div class="dot-key-holder">
                                <button class="dot-key key">.</button>
                            </div>
                        </div>
                        <div class="second-keys">
                            <button class="key">7</button>
                            <button class="key">8</button>
                            <button class="key">9</button>
                        </div>
                        <div class="third-keys">
                            <button class="key">4</button>
                            <button class="key">5</button>
                            <button class="key">6</button>
                        </div>
                        <div class="fourth-keys">
                            <button class="key">1</button>
                            <button class="key">2</button>
                            <button class="key">3</button>
                        </div>
                        <div class="fifth-keys">
                            <button class="plus">+</button>
                            <button class="zero key">0</button>
                            <button class="minus">-</button>
                        </div>
                    </div>
                    <div class="form">
                        <div class="temp_value" name="temperature" id="temperature">0</div>
                        <select name="from_temp" id="from_temp">
                            <option value="celsius">Celsius</option>
                            <option value="kelvin">Kelvin</option>
                            <option value="fahrenheit">Fahrenheit</option>
                        </select>
                        <br>
                        <div class="result" id="converted"></div>
                        <select name="to_temp" id="to_temp">
                            <option value="fahrenheit" selected>Fahrenheit</option>
                            <option value="celsius">Celsius</option>
                            <option value="kelvin">Kelvin</option>
                        </select>
                        <br>
                    </div>
                </div>
                <div class="attribution-holder">
                    <a class="attribution" href="boss.html">&copy; copyright 2023 coded by <span>Boss(Aniebiet)</span></a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>